### PR TITLE
Fix issue #3 - convert to string array

### PR DESCRIPTION
**Pull request by Soothsilver**

### CODE REVIEW

**Comment by gfraiteur** [comment]
https://postsharp.tpondemand.com/entity/3

**Comment by chrisbbe** [comment]
Will simply bumping the version of  NuGet/setup-nuget@v1.0.2 to v1.0.5 resolve the pipeline error?

**Comment by gfraiteur** [comment]
Thanks @Soothsilver.  I appreciate.

**Comment by chrisbbe** [comment]
Thanks. How and when will the NuGet be released?

**Pull request merged**
